"""
Agent Alerting System

This module implements comprehensive alerting capabilities for the per-core
agent coordination system, including alert generation, notification delivery,
escalation policies, and integration with external monitoring systems.

Key Features:
- Multi-channel alert delivery (email, webhook, log, console)
- Alert escalation and de-escalation policies
- Alert suppression and grouping
- Integration with external monitoring systems
- Customizable alert templates and formatting
"""

import json
import logging
import smtplib
import threading
import time
import uuid
from collections import defaultdict, deque
from dataclasses import dataclass, field
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set
from urllib.parse import urljoin
from urllib.request import Request, urlopen

from utils.per_core_agent_monitoring import Alert, AlertSeverity

logger = logging.getLogger(__name__)


class AlertChannel(Enum):
    """Alert delivery channels"""
    EMAIL = "email"
    WEBHOOK = "webhook"
    LOG = "log"
    CONSOLE = "console"
    SLACK = "slack"
    DISCORD = "discord"
    TEAMS = "teams"


class EscalationAction(Enum):
    """Escalation actions"""
    NOTIFY_ADDITIONAL = "notify_additional"
    INCREASE_FREQUENCY = "increase_frequency"
    CHANGE_CHANNEL = "change_channel"
    EXECUTE_COMMAND = "execute_command"


@dataclass
class AlertChannelConfig:
    """Configuration for an alert channel"""
    channel: AlertChannel
    enabled: bool = True
    config: Dict[str, Any] = field(default_factory=dict)
    
    # Channel-specific settings
    min_severity: AlertSeverity = AlertSeverity.INFO
    rate_limit_minutes: int = 5  # Minimum time between alerts
    batch_alerts: bool = False  # Group multiple alerts together
    template: Optional[str] = None  # Custom message template


@dataclass
class EscalationRule:
    """Escalation rule configuration"""
    name: str
    trigger_condition: str  # e.g., "unresolved_for_minutes > 30"
    action: EscalationAction
    action_config: Dict[str, Any] = field(default_factory=dict)
    max_escalations: int = 3
    escalation_interval_minutes: int = 30


@dataclass
class AlertSuppressionRule:
    """Alert suppression rule"""
    name: str
    condition: str  # e.g., "agent_id == 'core_0_security' and metric_name == 'success_rate'"
    duration_minutes: int = 60
    max_alerts_per_period: int = 1


@dataclass
class AlertDeliveryRecord:
    """Record of alert delivery"""
    alert_id: str
    channel: AlertChannel
    delivered_at: float
    success: bool
    error_message: Optional[str] = None
    delivery_time_ms: float = 0.0


class AlertFormatter:
    """Formats alerts for different channels"""
    
    @staticmethod
    def format_for_email(alert: Alert, template: Optional[str] = None) -> Dict[str, str]:
        """Format alert for email delivery"""
        if template:
            # Use custom template (would implement template engine here)
            subject = f"[{alert.severity.value.upper()}] {alert.title}"
            body = template.format(alert=alert)
        else:
            # Default email format
            subject = f"[{alert.severity.value.upper()}] {alert.title}"
            
            body = f"""
Alert Details:
--------------
Severity: {alert.severity.value.upper()}
Title: {alert.title}
Description: {alert.description}
Agent ID: {alert.agent_id or 'System'}
Metric: {alert.metric_name or 'N/A'}
Current Value: {alert.current_value or 'N/A'}
Threshold: {alert.threshold_value or 'N/A'}
Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime(alert.timestamp))}
Alert ID: {alert.alert_id}

This alert was generated by the Per-Core Agent Monitoring System.
"""
        
        return {"subject": subject, "body": body}
    
    @staticmethod
    def format_for_webhook(alert: Alert) -> Dict[str, Any]:
        """Format alert for webhook delivery"""
        return {
            "alert_id": alert.alert_id,
            "severity": alert.severity.value,
            "title": alert.title,
            "description": alert.description,
            "agent_id": alert.agent_id,
            "metric_name": alert.metric_name,
            "current_value": alert.current_value,
            "threshold_value": alert.threshold_value,
            "timestamp": alert.timestamp,
            "resolved": alert.resolved,
            "resolved_at": alert.resolved_at
        }
    
    @staticmethod
    def format_for_slack(alert: Alert) -> Dict[str, Any]:
        """Format alert for Slack delivery"""
        color_map = {
            AlertSeverity.INFO: "#36a64f",      # Green
            AlertSeverity.WARNING: "#ff9500",   # Orange
            AlertSeverity.ERROR: "#ff0000",     # Red
            AlertSeverity.CRITICAL: "#8b0000"   # Dark red
        }
        
        return {
            "text": f"Alert: {alert.title}",
            "attachments": [
                {
                    "color": color_map.get(alert.severity, "#cccccc"),
                    "fields": [
                        {"title": "Severity", "value": alert.severity.value.upper(), "short": True},
                        {"title": "Agent", "value": alert.agent_id or "System", "short": True},
                        {"title": "Metric", "value": alert.metric_name or "N/A", "short": True},
                        {"title": "Value", "value": str(alert.current_value or "N/A"), "short": True},
                        {"title": "Description", "value": alert.description, "short": False}
                    ],
                    "footer": "Per-Core Agent Monitor",
                    "ts": int(alert.timestamp)
                }
            ]
        }
    
    @staticmethod
    def format_for_console(alert: Alert) -> str:
        """Format alert for console output"""
        severity_symbols = {
            AlertSeverity.INFO: "ℹ️",
            AlertSeverity.WARNING: "⚠️",
            AlertSeverity.ERROR: "❌",
            AlertSeverity.CRITICAL: "🚨"
        }
        
        symbol = severity_symbols.get(alert.severity, "❓")
        timestamp_str = time.strftime('%H:%M:%S', time.localtime(alert.timestamp))
        
        return (f"{symbol} [{timestamp_str}] {alert.severity.value.upper()}: {alert.title}\n"
                f"   Agent: {alert.agent_id or 'System'} | {alert.description}")


class EmailAlertDelivery:
    """Email alert delivery implementation"""
    
    def __init__(self, smtp_host: str, smtp_port: int, username: str, password: str,
                 from_email: str, use_tls: bool = True):
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.username = username
        self.password = password
        self.from_email = from_email
        self.use_tls = use_tls
    
    def send_alert(self, alert: Alert, to_emails: List[str], template: Optional[str] = None) -> bool:
        """Send alert via email"""
        try:
            formatted = AlertFormatter.format_for_email(alert, template)
            
            msg = MIMEMultipart()
            msg['From'] = self.from_email
            msg['To'] = ', '.join(to_emails)
            msg['Subject'] = formatted['subject']
            
            msg.attach(MIMEText(formatted['body'], 'plain'))
            
            server = smtplib.SMTP(self.smtp_host, self.smtp_port)
            if self.use_tls:
                server.starttls()
            server.login(self.username, self.password)
            
            text = msg.as_string()
            server.sendmail(self.from_email, to_emails, text)
            server.quit()
            
            logger.info(f"Email alert sent successfully for {alert.alert_id}")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send email alert for {alert.alert_id}: {e}")
            return False


class WebhookAlertDelivery:
    """Webhook alert delivery implementation"""
    
    def __init__(self, webhook_url: str, headers: Optional[Dict[str, str]] = None,
                 timeout_seconds: int = 30):
        self.webhook_url = webhook_url
        self.headers = headers or {'Content-Type': 'application/json'}
        self.timeout_seconds = timeout_seconds
    
    def send_alert(self, alert: Alert) -> bool:
        """Send alert via webhook"""
        try:
            payload = AlertFormatter.format_for_webhook(alert)
            data = json.dumps(payload).encode('utf-8')
            
            request = Request(self.webhook_url, data=data, headers=self.headers)
            
            with urlopen(request, timeout=self.timeout_seconds) as response:
                if 200 <= response.getcode() < 300:
                    logger.info(f"Webhook alert sent successfully for {alert.alert_id}")
                    return True
                else:
                    logger.error(f"Webhook returned status {response.getcode()} for alert {alert.alert_id}")
                    return False
                    
        except Exception as e:
            logger.error(f"Failed to send webhook alert for {alert.alert_id}: {e}")
            return False


class SlackAlertDelivery:
    """Slack alert delivery implementation"""
    
    def __init__(self, webhook_url: str, channel: Optional[str] = None):
        self.webhook_url = webhook_url
        self.channel = channel
    
    def send_alert(self, alert: Alert) -> bool:
        """Send alert to Slack"""
        try:
            payload = AlertFormatter.format_for_slack(alert)
            if self.channel:
                payload['channel'] = self.channel
            
            data = json.dumps(payload).encode('utf-8')
            headers = {'Content-Type': 'application/json'}
            
            request = Request(self.webhook_url, data=data, headers=headers)
            
            with urlopen(request, timeout=30) as response:
                if 200 <= response.getcode() < 300:
                    logger.info(f"Slack alert sent successfully for {alert.alert_id}")
                    return True
                else:
                    logger.error(f"Slack webhook returned status {response.getcode()} for alert {alert.alert_id}")
                    return False
                    
        except Exception as e:
            logger.error(f"Failed to send Slack alert for {alert.alert_id}: {e}")
            return False


class AlertingSystem:
    """
    Comprehensive alerting system for per-core agent monitoring
    """
    
    def __init__(self):
        """Initialize the alerting system"""
        self.channels: Dict[str, AlertChannelConfig] = {}
        self.escalation_rules: List[EscalationRule] = []
        self.suppression_rules: List[AlertSuppressionRule] = []
        
        # Alert delivery implementations
        self.email_delivery: Optional[EmailAlertDelivery] = None
        self.webhook_deliveries: Dict[str, WebhookAlertDelivery] = {}
        self.slack_deliveries: Dict[str, SlackAlertDelivery] = {}
        
        # Alert tracking
        self.delivery_history: deque = deque(maxlen=10000)
        self.suppressed_alerts: Dict[str, List[float]] = defaultdict(list)  # rule_name -> timestamps
        self.escalation_state: Dict[str, Dict[str, Any]] = {}  # alert_id -> escalation info
        self.last_delivery_times: Dict[str, float] = {}  # channel_key -> timestamp
        
        # Threading
        self._delivery_queue: deque = deque()
        self._delivery_thread: Optional[threading.Thread] = None
        self._shutdown = False
        self._queue_lock = threading.Lock()
        
        logger.info("AlertingSystem initialized")
    
    def configure_email_channel(self, smtp_host: str, smtp_port: int, username: str,
                               password: str, from_email: str, to_emails: List[str],
                               min_severity: AlertSeverity = AlertSeverity.WARNING,
                               use_tls: bool = True) -> None:
        """Configure email alert channel"""
        self.email_delivery = EmailAlertDelivery(
            smtp_host, smtp_port, username, password, from_email, use_tls
        )
        
        self.channels['email'] = AlertChannelConfig(
            channel=AlertChannel.EMAIL,
            enabled=True,
            min_severity=min_severity,
            config={'to_emails': to_emails}
        )
        
        logger.info(f"Email alerting configured for {len(to_emails)} recipients")
    
    def configure_webhook_channel(self, name: str, webhook_url: str,
                                 headers: Optional[Dict[str, str]] = None,
                                 min_severity: AlertSeverity = AlertSeverity.WARNING) -> None:
        """Configure webhook alert channel"""
        self.webhook_deliveries[name] = WebhookAlertDelivery(webhook_url, headers)
        
        self.channels[f'webhook_{name}'] = AlertChannelConfig(
            channel=AlertChannel.WEBHOOK,
            enabled=True,
            min_severity=min_severity,
            config={'webhook_name': name}
        )
        
        logger.info(f"Webhook alerting configured: {name}")
    
    def configure_slack_channel(self, name: str, webhook_url: str, channel: Optional[str] = None,
                               min_severity: AlertSeverity = AlertSeverity.WARNING) -> None:
        """Configure Slack alert channel"""
        self.slack_deliveries[name] = SlackAlertDelivery(webhook_url, channel)
        
        self.channels[f'slack_{name}'] = AlertChannelConfig(
            channel=AlertChannel.SLACK,
            enabled=True,
            min_severity=min_severity,
            config={'slack_name': name, 'channel': channel}
        )
        
        logger.info(f"Slack alerting configured: {name}")
    
    def add_escalation_rule(self, rule: EscalationRule) -> None:
        """Add an escalation rule"""
        self.escalation_rules.append(rule)
        logger.info(f"Added escalation rule: {rule.name}")
    
    def add_suppression_rule(self, rule: AlertSuppressionRule) -> None:
        """Add an alert suppression rule"""
        self.suppression_rules.append(rule)
        logger.info(f"Added suppression rule: {rule.name}")
    
    def start_delivery_service(self) -> None:
        """Start the alert delivery service"""
        if self._delivery_thread and self._delivery_thread.is_alive():
            logger.warning("Alert delivery service is already running")
            return
        
        self._shutdown = False
        self._delivery_thread = threading.Thread(
            target=self._delivery_loop,
            daemon=True,
            name="AlertDeliveryService"
        )
        self._delivery_thread.start()
        
        logger.info("Alert delivery service started")
    
    def stop_delivery_service(self) -> None:
        """Stop the alert delivery service"""
        self._shutdown = True
        if self._delivery_thread and self._delivery_thread.is_alive():
            self._delivery_thread.join(timeout=10)
        
        logger.info("Alert delivery service stopped")
    
    def process_alert(self, alert: Alert) -> None:
        """Process an incoming alert"""
        logger.debug(f"Processing alert: {alert.alert_id}")
        
        # Check suppression rules
        if self._is_alert_suppressed(alert):
            logger.info(f"Alert {alert.alert_id} suppressed by rules")
            return
        
        # Queue alert for delivery
        with self._queue_lock:
            self._delivery_queue.append(alert)
        
        # Check for escalation
        self._check_escalation(alert)
    
    def resolve_alert(self, alert: Alert) -> None:
        """Handle alert resolution"""
        logger.info(f"Alert resolved: {alert.alert_id}")
        
        # Remove from escalation tracking
        if alert.alert_id in self.escalation_state:
            del self.escalation_state[alert.alert_id]
        
        # Optionally send resolution notification
        if self._should_notify_resolution(alert):
            resolution_alert = Alert(
                alert_id=f"{alert.alert_id}_resolved",
                severity=AlertSeverity.INFO,
                title=f"RESOLVED: {alert.title}",
                description=f"Alert has been resolved: {alert.description}",
                agent_id=alert.agent_id,
                metric_name=alert.metric_name
            )
            
            with self._queue_lock:
                self._delivery_queue.append(resolution_alert)
    
    def get_delivery_statistics(self) -> Dict[str, Any]:
        """Get alert delivery statistics"""
        total_deliveries = len(self.delivery_history)
        successful_deliveries = len([d for d in self.delivery_history if d.success])
        
        channel_stats = defaultdict(lambda: {"total": 0, "successful": 0})
        
        for delivery in self.delivery_history:
            channel_stats[delivery.channel.value]["total"] += 1
            if delivery.success:
                channel_stats[delivery.channel.value]["successful"] += 1
        
        return {
            "total_deliveries": total_deliveries,
            "successful_deliveries": successful_deliveries,
            "success_rate": successful_deliveries / total_deliveries if total_deliveries > 0 else 0.0,
            "channel_statistics": dict(channel_stats),
            "active_escalations": len(self.escalation_state),
            "suppression_rules_active": len(self.suppression_rules)
        }
    
    def _delivery_loop(self) -> None:
        """Main alert delivery loop"""
        logger.info("Alert delivery loop started")
        
        while not self._shutdown:
            try:
                # Process queued alerts
                alerts_to_process = []
                with self._queue_lock:
                    while self._delivery_queue:
                        alerts_to_process.append(self._delivery_queue.popleft())
                
                for alert in alerts_to_process:
                    self._deliver_alert(alert)
                
                # Check for escalations
                self._process_escalations()
                
                # Clean up old suppression records
                self._cleanup_suppression_records()
                
                time.sleep(5)  # Check every 5 seconds
                
            except Exception as e:
                logger.error(f"Error in alert delivery loop: {e}")
                time.sleep(10)
        
        logger.info("Alert delivery loop stopped")
    
    def _deliver_alert(self, alert: Alert) -> None:
        """Deliver an alert through configured channels"""
        for channel_name, channel_config in self.channels.items():
            if not channel_config.enabled:
                continue
            
            # Check severity threshold
            if alert.severity.value < channel_config.min_severity.value:
                continue
            
            # Check rate limiting
            if self._is_rate_limited(channel_name, channel_config):
                continue
            
            # Deliver through appropriate channel
            delivery_start = time.time()
            success = False
            error_message = None
            
            try:
                if channel_config.channel == AlertChannel.EMAIL:
                    success = self._deliver_email(alert, channel_config)
                elif channel_config.channel == AlertChannel.WEBHOOK:
                    success = self._deliver_webhook(alert, channel_config)
                elif channel_config.channel == AlertChannel.SLACK:
                    success = self._deliver_slack(alert, channel_config)
                elif channel_config.channel == AlertChannel.LOG:
                    success = self._deliver_log(alert)
                elif channel_config.channel == AlertChannel.CONSOLE:
                    success = self._deliver_console(alert)
                
            except Exception as e:
                error_message = str(e)
                logger.error(f"Error delivering alert {alert.alert_id} via {channel_name}: {e}")
            
            # Record delivery
            delivery_time = (time.time() - delivery_start) * 1000
            delivery_record = AlertDeliveryRecord(
                alert_id=alert.alert_id,
                channel=channel_config.channel,
                delivered_at=time.time(),
                success=success,
                error_message=error_message,
                delivery_time_ms=delivery_time
            )
            
            self.delivery_history.append(delivery_record)
            
            # Update rate limiting
            if success:
                self.last_delivery_times[channel_name] = time.time()
    
    def _deliver_email(self, alert: Alert, channel_config: AlertChannelConfig) -> bool:
        """Deliver alert via email"""
        if not self.email_delivery:
            return False
        
        to_emails = channel_config.config.get('to_emails', [])
        template = channel_config.template
        
        return self.email_delivery.send_alert(alert, to_emails, template)
    
    def _deliver_webhook(self, alert: Alert, channel_config: AlertChannelConfig) -> bool:
        """Deliver alert via webhook"""
        webhook_name = channel_config.config.get('webhook_name')
        if not webhook_name or webhook_name not in self.webhook_deliveries:
            return False
        
        return self.webhook_deliveries[webhook_name].send_alert(alert)
    
    def _deliver_slack(self, alert: Alert, channel_config: AlertChannelConfig) -> bool:
        """Deliver alert via Slack"""
        slack_name = channel_config.config.get('slack_name')
        if not slack_name or slack_name not in self.slack_deliveries:
            return False
        
        return self.slack_deliveries[slack_name].send_alert(alert)
    
    def _deliver_log(self, alert: Alert) -> bool:
        """Deliver alert via logging"""
        try:
            log_level = {
                AlertSeverity.INFO: logging.INFO,
                AlertSeverity.WARNING: logging.WARNING,
                AlertSeverity.ERROR: logging.ERROR,
                AlertSeverity.CRITICAL: logging.CRITICAL
            }.get(alert.severity, logging.INFO)
            
            logger.log(log_level, f"ALERT: {alert.title} - {alert.description} (Agent: {alert.agent_id or 'System'})")
            return True
            
        except Exception:
            return False
    
    def _deliver_console(self, alert: Alert) -> bool:
        """Deliver alert via console output"""
        try:
            formatted_alert = AlertFormatter.format_for_console(alert)
            print(formatted_alert)
            return True
            
        except Exception:
            return False
    
    def _is_alert_suppressed(self, alert: Alert) -> bool:
        """Check if alert should be suppressed"""
        current_time = time.time()
        
        for rule in self.suppression_rules:
            if self._matches_suppression_condition(alert, rule.condition):
                # Check if we're within the suppression period
                rule_timestamps = self.suppressed_alerts[rule.name]
                
                # Clean old timestamps
                cutoff_time = current_time - (rule.duration_minutes * 60)
                rule_timestamps[:] = [ts for ts in rule_timestamps if ts > cutoff_time]
                
                # Check if we've exceeded the max alerts for this period
                if len(rule_timestamps) >= rule.max_alerts_per_period:
                    return True
                
                # Record this alert
                rule_timestamps.append(current_time)
        
        return False
    
    def _matches_suppression_condition(self, alert: Alert, condition: str) -> bool:
        """Check if alert matches suppression condition"""
        # Simple condition matching (would implement proper expression parser in production)
        try:
            # Create a context with alert properties
            context = {
                'agent_id': alert.agent_id,
                'metric_name': alert.metric_name,
                'severity': alert.severity.value,
                'title': alert.title
            }
            
            # Evaluate condition (simplified - would use proper expression evaluator)
            return eval(condition, {"__builtins__": {}}, context)
            
        except Exception as e:
            logger.warning(f"Error evaluating suppression condition '{condition}': {e}")
            return False
    
    def _is_rate_limited(self, channel_name: str, channel_config: AlertChannelConfig) -> bool:
        """Check if channel is rate limited"""
        if channel_config.rate_limit_minutes <= 0:
            return False
        
        last_delivery = self.last_delivery_times.get(channel_name, 0)
        time_since_last = time.time() - last_delivery
        
        return time_since_last < (channel_config.rate_limit_minutes * 60)
    
    def _check_escalation(self, alert: Alert) -> None:
        """Check if alert needs escalation"""
        if alert.alert_id not in self.escalation_state:
            self.escalation_state[alert.alert_id] = {
                'first_seen': time.time(),
                'escalation_count': 0,
                'last_escalation': 0
            }
    
    def _process_escalations(self) -> None:
        """Process escalation rules for active alerts"""
        current_time = time.time()
        
        for alert_id, escalation_info in list(self.escalation_state.items()):
            for rule in self.escalation_rules:
                if self._should_escalate(alert_id, escalation_info, rule, current_time):
                    self._execute_escalation(alert_id, rule, escalation_info)
    
    def _should_escalate(self, alert_id: str, escalation_info: Dict[str, Any],
                        rule: EscalationRule, current_time: float) -> bool:
        """Check if alert should be escalated"""
        # Check if we've exceeded max escalations
        if escalation_info['escalation_count'] >= rule.max_escalations:
            return False
        
        # Check if enough time has passed since last escalation
        time_since_last = current_time - escalation_info.get('last_escalation', 0)
        if time_since_last < (rule.escalation_interval_minutes * 60):
            return False
        
        # Check trigger condition (simplified)
        unresolved_minutes = (current_time - escalation_info['first_seen']) / 60
        
        if rule.trigger_condition == "unresolved_for_minutes > 30":
            return unresolved_minutes > 30
        
        # Add more condition checks as needed
        return False
    
    def _execute_escalation(self, alert_id: str, rule: EscalationRule,
                           escalation_info: Dict[str, Any]) -> None:
        """Execute escalation action"""
        logger.warning(f"Escalating alert {alert_id} using rule {rule.name}")
        
        escalation_info['escalation_count'] += 1
        escalation_info['last_escalation'] = time.time()
        
        # Execute escalation action based on type
        if rule.action == EscalationAction.NOTIFY_ADDITIONAL:
            # Would implement additional notification logic
            pass
        elif rule.action == EscalationAction.INCREASE_FREQUENCY:
            # Would implement frequency increase logic
            pass
        elif rule.action == EscalationAction.CHANGE_CHANNEL:
            # Would implement channel change logic
            pass
        elif rule.action == EscalationAction.EXECUTE_COMMAND:
            # Would implement command execution logic
            pass
    
    def _should_notify_resolution(self, alert: Alert) -> bool:
        """Check if resolution should be notified"""
        # Only notify resolution for ERROR and CRITICAL alerts
        return alert.severity in [AlertSeverity.ERROR, AlertSeverity.CRITICAL]
    
    def _cleanup_suppression_records(self) -> None:
        """Clean up old suppression records"""
        current_time = time.time()
        
        for rule in self.suppression_rules:
            cutoff_time = current_time - (rule.duration_minutes * 60)
            rule_timestamps = self.suppressed_alerts[rule.name]
            rule_timestamps[:] = [ts for ts in rule_timestamps if ts > cutoff_time]


# Global alerting system instance
_global_alerting_system: Optional[AlertingSystem] = None


def get_alerting_system() -> AlertingSystem:
    """Get the global alerting system instance"""
    global _global_alerting_system
    if _global_alerting_system is None:
        _global_alerting_system = AlertingSystem()
    return _global_alerting_system


def initialize_alerting(email_config: Optional[Dict[str, Any]] = None,
                       webhook_configs: Optional[List[Dict[str, Any]]] = None,
                       slack_configs: Optional[List[Dict[str, Any]]] = None) -> AlertingSystem:
    """
    Initialize the global alerting system
    
    Args:
        email_config: Email configuration dictionary
        webhook_configs: List of webhook configurations
        slack_configs: List of Slack configurations
        
    Returns:
        Initialized alerting system
    """
    global _global_alerting_system
    _global_alerting_system = AlertingSystem()
    
    # Configure email if provided
    if email_config:
        _global_alerting_system.configure_email_channel(**email_config)
    
    # Configure webhooks if provided
    if webhook_configs:
        for config in webhook_configs:
            _global_alerting_system.configure_webhook_channel(**config)
    
    # Configure Slack if provided
    if slack_configs:
        for config in slack_configs:
            _global_alerting_system.configure_slack_channel(**config)
    
    # Start delivery service
    _global_alerting_system.start_delivery_service()
    
    return _global_alerting_system


def shutdown_alerting() -> None:
    """Shutdown the global alerting system"""
    global _global_alerting_system
    if _global_alerting_system:
        _global_alerting_system.stop_delivery_service()
        _global_alerting_system = None